# Usa imagen base oficial con Python
FROM mcr.microsoft.com/devcontainers/python:3.11

# Instala las extensiones necesarias
RUN pip install azure-ai-textanalytics azure-ai-vision azure-cognitiveservices-vision-computervision azure-ai-language-conversations
